const LANGUAGE_DATA_EASY = {
    "Acehnese": [
        "Austronesian",
        "Malayo-Polynesian",
        "Malayo-Chamic",
        "Aceh-Chamic",
        "Acehnese"
    ],
    "Akan": [
        "Atlantic-Congo",
        "Volta-Congo",
        "Kwa Volta-Congo",
        "Nyo",
        "Potou-Tano",
        "Tano",
        "Central Tano",
        "Akanic",
        "Akan"
    ],
    "Awadhi": [
        "Indo-European",
        "Classical Indo-European",
        "Indo-Iranian",
        "Indo-Aryan",
        "Middle-Modern Indo-Aryan",
        "Continental Indo-Aryan",
        "Midlands Indo-Aryan",
        "Shaurasenic",
        "Eastern Hindi",
        "Awadhic",
        "Awadhi"
    ],
    "Baoulé": [
        "Atlantic-Congo",
        "Volta-Congo",
        "Kwa Volta-Congo",
        "Nyo",
        "Potou-Tano",
        "Tano",
        "Central Tano",
        "Bia",
        "Northern Bia",
        "Baoulé"
    ],
    "Bashkir": [
        "Turkic",
        "Common Turkic",
        "Kipchak-Turkestan",
        "Kipchak",
        "Northwest Kipchak",
        "North Kipchak",
        "Bashkiric",
        "Bashkir"
    ],
    "Bavarian": [
        "Indo-European",
        "Classical Indo-European",
        "Germanic",
        "Northwest Germanic",
        "West Germanic",
        "High German",
        "Upper German",
        "Middle-Modern High German",
        "Modern High German",
        "Bairisch",
        "Bavarian"
    ],
    "Beja": [
        "Afro-Asiatic",
        "Cushitic",
        "Beja"
    ],
    "Belarusian": [
        "Indo-European",
        "Classical Indo-European",
        "Balto-Slavic",
        "Slavic",
        "East Slavic",
        "Belarusian"
    ],
    "Bouyei": [
        "Tai-Kadai",
        "Kam-Tai",
        "Daic-Beic",
        "Daic",
        "Northern Daic-Sek",
        "Northern Daic",
        "Northern Tai",
        "Bouyei"
    ],
    "Bulgarian": [
        "Indo-European",
        "Classical Indo-European",
        "Balto-Slavic",
        "Slavic",
        "South Slavic",
        "Eastern South Slavic",
        "Macedo-Bulgarian",
        "Bulgarian"
    ],
    "Cameroon Pidgin": [
        "Indo-European",
        "Classical Indo-European",
        "Germanic",
        "Northwest Germanic",
        "West Germanic",
        "North Sea Germanic",
        "Anglo-Frisian",
        "Anglic",
        "Later Anglic",
        "Middle-Modern English",
        "Macro-English",
        "Guinea Coast Creole English",
        "West African Creole English",
        "Coastal Nigerian Krio",
        "Nigeria-Cameroon Creole English",
        "Cameroon Pidgin"
    ],
    "Catalan": [
        "Indo-European",
        "Classical Indo-European",
        "Italic",
        "Latino-Faliscan",
        "Latinic",
        "Imperial Latin",
        "Romance",
        "Italo-Western Romance",
        "Western Romance",
        "Shifted Western Romance",
        "Southwestern Shifted Romance",
        "Catalan"
    ],
    "Cebuano": [
        "Austronesian",
        "Malayo-Polynesian",
        "Greater Central Philippine",
        "Central Philippine",
        "Bisayan",
        "Cebuano"
    ],
    "Chittagonian": [
        "Indo-European",
        "Classical Indo-European",
        "Indo-Iranian",
        "Indo-Aryan",
        "Middle-Modern Indo-Aryan",
        "Continental Indo-Aryan",
        "Indo-Aryan Eastern zone",
        "Oriya-Gauda-Kamrupa",
        "Gauda-Kamrupa",
        "Gauda-Banga",
        "Southeastern Bengali",
        "Chittagonian"
    ],
    "Congo Swahili": [
        "Atlantic-Congo",
        "Volta-Congo",
        "Benue-Congo",
        "Bantoid",
        "Southern Bantoid",
        "Narrow Bantu",
        "East Bantu",
        "Northeast Savanna Bantu",
        "Northeast Coastal Bantu",
        "Coastal NEC Bantu",
        "Sabaki-Swahili",
        "Swahili (G.40)",
        "Mombasa-Lamu-Inland Swahili",
        "Congo Swahili"
    ],
    "Dagbani": [
        "Atlantic-Congo",
        "Volta-Congo",
        "North Volta-Congo",
        "Gur",
        "Central Gur",
        "Northern Central Gur",
        "Bwamu-Oti-Volta",
        "Oti-Volta",
        "Nuclear Oti-Volta",
        "Gurma-Yom-Oti-Volta Occidental",
        "Oti-Volta Occidental",
        "Nuclear Oti-Volta Occidental",
        "Southeast Western Oti-Volta",
        "Mampruli-Dagbani",
        "Dagbani"
    ],
    "Eastern Tamang": [
        "Sino-Tibetan",
        "Bodic",
        "Kaike-Ghale-Tamangic",
        "Ghale-Tamangic",
        "Tamangic",
        "Nuclear Tamang",
        "Eastern Tamang"
    ],
    "Efik": [
        "Atlantic-Congo",
        "Volta-Congo",
        "Benue-Congo",
        "Delta Cross",
        "Lower Cross",
        "Nuclear Lower Cross",
        "Central Lower Cross",
        "Efikic",
        "Okop Usem",
        "Efik-Ibibio",
        "Efik"
    ],
    "English": [
        "Indo-European",
        "Classical Indo-European",
        "Germanic",
        "Northwest Germanic",
        "West Germanic",
        "North Sea Germanic",
        "Anglo-Frisian",
        "Anglic",
        "Later Anglic",
        "Middle-Modern English",
        "Macro-English",
        "English"
    ],
    "Fon": [
        "Atlantic-Congo",
        "Volta-Congo",
        "Kwa Volta-Congo",
        "Gbe",
        "Eastern Gbe",
        "Fongbeic",
        "Fon"
    ],
    "French": [
        "Indo-European",
        "Classical Indo-European",
        "Italic",
        "Latino-Faliscan",
        "Latinic",
        "Imperial Latin",
        "Romance",
        "Italo-Western Romance",
        "Western Romance",
        "Shifted Western Romance",
        "Northwestern Shifted Romance",
        "Gallo-Rhaetian",
        "Oil",
        "Central Oil",
        "Macro-French",
        "Global French",
        "French"
    ],
    "Galician": [
        "Indo-European",
        "Classical Indo-European",
        "Italic",
        "Latino-Faliscan",
        "Latinic",
        "Imperial Latin",
        "Romance",
        "Italo-Western Romance",
        "Western Romance",
        "Shifted Western Romance",
        "Southwestern Shifted Romance",
        "West Ibero-Romance",
        "Galician Romance",
        "Galician"
    ],
    "German": [
        "Indo-European",
        "Classical Indo-European",
        "Germanic",
        "Northwest Germanic",
        "West Germanic",
        "High German",
        "Upper German",
        "Middle-Modern High German",
        "Modern High German",
        "Upper Franconian",
        "Global German",
        "German"
    ],
    "Ghanaian Pidgin English": [
        "Indo-European",
        "Classical Indo-European",
        "Germanic",
        "Northwest Germanic",
        "West Germanic",
        "North Sea Germanic",
        "Anglo-Frisian",
        "Anglic",
        "Later Anglic",
        "Middle-Modern English",
        "Macro-English",
        "Guinea Coast Creole English",
        "West African Creole English",
        "Coastal Nigerian Krio",
        "Ghanaian Pidgin English"
    ],
    "Gilaki": [
        "Indo-European",
        "Classical Indo-European",
        "Indo-Iranian",
        "Iranian",
        "Central Iranian PBS",
        "Central Iranian PB",
        "Northwestern Iranian",
        "Caspian",
        "Gilaki-Rudbari",
        "Gilaki"
    ],
    "Goan Konkani": [
        "Indo-European",
        "Classical Indo-European",
        "Indo-Iranian",
        "Indo-Aryan",
        "Middle-Modern Indo-Aryan",
        "Continental Indo-Aryan",
        "Indo-Aryan Southern zone",
        "Marathic",
        "Marathi-Konkani",
        "Goan Konkani"
    ],
    "Hainanese": [
        "Sino-Tibetan",
        "Sinitic",
        "Min",
        "Coastal Min",
        "Southern Min-Pu-Xian",
        "Southern Min",
        "Leiqiong",
        "Hainanese"
    ],
    "Ho": [
        "Austroasiatic",
        "Mundaic",
        "North Munda",
        "Kherwarian",
        "Mundaric",
        "Ho-Mundari",
        "Ho"
    ],
    "Hungarian": [
        "Uralic",
        "Hungaric",
        "Hungarian"
    ],
    "Iban": [
        "Austronesian",
        "Malayo-Polynesian",
        "Malayo-Chamic",
        "Malayic",
        "Ibanic",
        "Iban-Mualang-Seberuang",
        "Iban-Seberuang",
        "Northern Iban",
        "Iban"
    ],
    "Igbo": [
        "Atlantic-Congo",
        "Volta-Congo",
        "Benue-Congo",
        "Igboid",
        "Nuclear Igboid",
        "Central-Northern Igbo",
        "Igbo"
    ],
    "Javanese": [
        "Austronesian",
        "Malayo-Polynesian",
        "Javanesic",
        "Modern Javanese",
        "Global Javanese",
        "Javanese"
    ],
    "Kafa": [
        "Ta-Ne-Omotic",
        "Kefoid",
        "South Gonga",
        "Kafa"
    ],
    "Kam": [
        "Atlantic-Congo",
        "Volta-Congo",
        "North Volta-Congo",
        "Kam"
    ],
    "Kelantan-Pattani Malay": [
        "Austronesian",
        "Malayo-Polynesian",
        "Malayo-Chamic",
        "Malayic",
        "Nuclear Malayic",
        "Greater Riau-Johoric",
        "Northeastern Peninsular Malay",
        "Kelantan-Pattani Malay"
    ],
    "Khams Tibetan": [
        "Sino-Tibetan",
        "Bodic",
        "Bodish",
        "Early Old Tibetan",
        "Middle Old Tibetan",
        "Late Old Tibetan",
        "Kham-Hor",
        "Khams Tibetan"
    ],
    "Kurukh": [
        "Dravidian",
        "North Dravidian",
        "Kurux-Malto",
        "Kurukh"
    ],
    "Laki": [
        "Indo-European",
        "Classical Indo-European",
        "Indo-Iranian",
        "Iranian",
        "Central Iranian PBS",
        "Central Iranian PB",
        "Northwestern Iranian",
        "Laki-Kurdish",
        "Laki"
    ],
    "Lao": [
        "Tai-Kadai",
        "Kam-Tai",
        "Daic-Beic",
        "Daic",
        "Central-Southwestern Tai",
        "Wenma-Southwestern Tai",
        "Sapa-Southwestern Tai",
        "Southwestern Tai",
        "Southwestern Thai PH",
        "Lao-Thai",
        "Lao"
    ],
    "Latvian": [
        "Indo-European",
        "Classical Indo-European",
        "Balto-Slavic",
        "Eastern Baltic",
        "Latvian"
    ],
    "Levantine Arabic": [
        "Afro-Asiatic",
        "Semitic",
        "West Semitic",
        "Central Semitic",
        "Arabian",
        "Arabic",
        "Levantine-Cypriot Arabic",
        "Levantine Arabic"
    ],
    "Libyan Arabic": [
        "Afro-Asiatic",
        "Semitic",
        "West Semitic",
        "Central Semitic",
        "Arabian",
        "Arabic",
        "North African Arabic",
        "Libyan Arabic"
    ],
    "Lithuanian": [
        "Indo-European",
        "Classical Indo-European",
        "Balto-Slavic",
        "Eastern Baltic",
        "Lithuanian"
    ],
    "Macedonian": [
        "Indo-European",
        "Classical Indo-European",
        "Balto-Slavic",
        "Slavic",
        "South Slavic",
        "Eastern South Slavic",
        "Macedo-Bulgarian",
        "Macedonian"
    ],
    "Maguindanao": [
        "Austronesian",
        "Malayo-Polynesian",
        "Greater Central Philippine",
        "Danaw",
        "Maguindanao"
    ],
    "Makonde": [
        "Atlantic-Congo",
        "Volta-Congo",
        "Benue-Congo",
        "Bantoid",
        "Southern Bantoid",
        "Narrow Bantu",
        "East Bantu",
        "Rufiji-Ruvuma",
        "Ruvuma",
        "Makonde-Makwe",
        "Makonde"
    ],
    "Mazanderani": [
        "Indo-European",
        "Classical Indo-European",
        "Indo-Iranian",
        "Iranian",
        "Central Iranian PBS",
        "Central Iranian PB",
        "Northwestern Iranian",
        "Caspian",
        "Mazanderani-Shahmirzadi",
        "Mazanderani"
    ],
    "Merwari": [
        "Indo-European",
        "Classical Indo-European",
        "Indo-Iranian",
        "Indo-Aryan",
        "Middle-Modern Indo-Aryan",
        "Continental Indo-Aryan",
        "Midlands Indo-Aryan",
        "Apabhramsic",
        "Gujarati-Rajasthani",
        "Rajasthani",
        "Merwari"
    ],
    "Mewati": [
        "Indo-European",
        "Classical Indo-European",
        "Indo-Iranian",
        "Indo-Aryan",
        "Middle-Modern Indo-Aryan",
        "Continental Indo-Aryan",
        "Midlands Indo-Aryan",
        "Apabhramsic",
        "Gujarati-Rajasthani",
        "Rajasthani",
        "Mewati-Gojri",
        "Mewati"
    ],
    "Minangkabau": [
        "Austronesian",
        "Malayo-Polynesian",
        "Malayo-Chamic",
        "Malayic",
        "Nuclear Malayic",
        "Northern Sumatra Malay",
        "Kerinci-Minangkabau",
        "Minangkabauic",
        "Minangkabau"
    ],
    "Modern Greek": [
        "Indo-European",
        "Classical Indo-European",
        "Graeco-Phrygian",
        "Greek",
        "South Greek",
        "Central Greek",
        "Koineic Greek",
        "Modern Koineic Greek",
        "Nuclear Modern Greek",
        "Modern Greek"
    ],
    "Moroccan Arabic": [
        "Afro-Asiatic",
        "Semitic",
        "West Semitic",
        "Central Semitic",
        "Arabian",
        "Arabic",
        "North African Arabic",
        "Moroccan-Andalusian Arabic",
        "Moroccan Arabic"
    ],
    "Muong": [
        "Austroasiatic",
        "Vietic",
        "Viet-Muong",
        "Muongic",
        "Muong"
    ],
    "Negeri Sembilan Malay": [
        "Austronesian",
        "Malayo-Polynesian",
        "Malayo-Chamic",
        "Malayic",
        "Nuclear Malayic",
        "Northern Sumatra Malay",
        "Kerinci-Minangkabau",
        "Minangkabauic",
        "Negeri Sembilan Malay"
    ],
    "Nigerian Pidgin": [
        "Indo-European",
        "Classical Indo-European",
        "Germanic",
        "Northwest Germanic",
        "West Germanic",
        "North Sea Germanic",
        "Anglo-Frisian",
        "Anglic",
        "Later Anglic",
        "Middle-Modern English",
        "Macro-English",
        "Guinea Coast Creole English",
        "West African Creole English",
        "Coastal Nigerian Krio",
        "Nigeria-Cameroon Creole English",
        "Nigerian Pidgin"
    ],
    "Nimadi": [
        "Indo-European",
        "Classical Indo-European",
        "Indo-Iranian",
        "Indo-Aryan",
        "Middle-Modern Indo-Aryan",
        "Continental Indo-Aryan",
        "Midlands Indo-Aryan",
        "Bhil",
        "Nimadi"
    ],
    "Northern Khmer": [
        "Austroasiatic",
        "Khmeric",
        "Northern Khmer"
    ],
    "Norwegian": [
        "Indo-European",
        "Classical Indo-European",
        "Germanic",
        "Northwest Germanic",
        "North Germanic",
        "West Scandinavian",
        "Norwegian"
    ],
    "Odia": [
        "Indo-European",
        "Classical Indo-European",
        "Indo-Iranian",
        "Indo-Aryan",
        "Middle-Modern Indo-Aryan",
        "Continental Indo-Aryan",
        "Indo-Aryan Eastern zone",
        "Oriya-Gauda-Kamrupa",
        "Macro-Oriya",
        "Odia"
    ],
    "Pulaar": [
        "Atlantic-Congo",
        "North-Central Atlantic",
        "Fula-Sereer",
        "Fula",
        "Pulaar"
    ],
    "Romagnol": [
        "Indo-European",
        "Classical Indo-European",
        "Italic",
        "Latino-Faliscan",
        "Latinic",
        "Imperial Latin",
        "Romance",
        "Italo-Western Romance",
        "Western Romance",
        "Shifted Western Romance",
        "Northwestern Shifted Romance",
        "Gallo-Italian",
        "Emiliano-Romagnolo",
        "Romagnol"
    ],
    "Russian": [
        "Indo-European",
        "Classical Indo-European",
        "Balto-Slavic",
        "Slavic",
        "East Slavic",
        "Russian"
    ],
    "S'gaw Karen": [
        "Sino-Tibetan",
        "Karenic",
        "Southern Karen",
        "Sgaw",
        "S'gaw Karen"
    ],
    "Sambalpuri": [
        "Indo-European",
        "Classical Indo-European",
        "Indo-Iranian",
        "Indo-Aryan",
        "Middle-Modern Indo-Aryan",
        "Continental Indo-Aryan",
        "Indo-Aryan Eastern zone",
        "Oriya-Gauda-Kamrupa",
        "Macro-Oriya",
        "Sambalpuri"
    ],
    "Sango": [
        "Atlantic-Congo",
        "Volta-Congo",
        "North Volta-Congo",
        "Cameroun-Ubangian",
        "Ubangi",
        "Ngbandi-Mongoba-Kazibati",
        "Ngbandic",
        "Nuclear Ngbandic",
        "Sangoic",
        "Sango"
    ],
    "Sebat Bet Gurage": [
        "Afro-Asiatic",
        "Semitic",
        "West Semitic",
        "Ethiosemitic",
        "South Ethiopic",
        "Outer South Ethiopic",
        "TT-Group",
        "Sebat Bet Gurage"
    ],
    "Shilluk": [
        "Nilotic",
        "Western Nilotic",
        "Lwoo",
        "Northern Lwoo",
        "Shilluk"
    ],
    "Slovak": [
        "Indo-European",
        "Classical Indo-European",
        "Balto-Slavic",
        "Slavic",
        "West Slavic",
        "Czech-Slovak",
        "Slovak"
    ],
    "South Azerbaijani": [
        "Turkic",
        "Common Turkic",
        "Oghuz",
        "Nuclear Oghuz",
        "Central Oghuz",
        "South Azerbaijani"
    ],
    "South Bolivian Quechua": [
        "Quechuan",
        "Southern Quechua",
        "Bolivian-Argentinian Quechua",
        "South Bolivian-Argentinian Quechua",
        "South Bolivian Quechua"
    ],
    "Southern Kurdish": [
        "Indo-European",
        "Classical Indo-European",
        "Indo-Iranian",
        "Iranian",
        "Central Iranian PBS",
        "Central Iranian PB",
        "Northwestern Iranian",
        "Laki-Kurdish",
        "Kurdish",
        "Southern Kurdish"
    ],
    "Southern Thai": [
        "Tai-Kadai",
        "Kam-Tai",
        "Daic-Beic",
        "Daic",
        "Central-Southwestern Tai",
        "Wenma-Southwestern Tai",
        "Sapa-Southwestern Tai",
        "Southwestern Tai",
        "Southwestern Thai PH",
        "Lao-Thai",
        "Southern Thai"
    ],
    "Spanish": [
        "Indo-European",
        "Classical Indo-European",
        "Italic",
        "Latino-Faliscan",
        "Latinic",
        "Imperial Latin",
        "Romance",
        "Italo-Western Romance",
        "Western Romance",
        "Shifted Western Romance",
        "Southwestern Shifted Romance",
        "West Ibero-Romance",
        "Castilic",
        "Spanish"
    ],
    "Sukuma": [
        "Atlantic-Congo",
        "Volta-Congo",
        "Benue-Congo",
        "Bantoid",
        "Southern Bantoid",
        "Narrow Bantu",
        "East Bantu",
        "Northeast Savanna Bantu",
        "Sukuma-Nyamwezi (F.20)",
        "Nyamwezic",
        "Sukuma"
    ],
    "Sundanese": [
        "Austronesian",
        "Malayo-Polynesian",
        "Sundanese"
    ],
    "Susu": [
        "Mande",
        "Western Mande",
        "Manding-Kpelle",
        "Central Mande",
        "Susu-Yalunka",
        "Susu"
    ],
    "Swahili": [
        "Atlantic-Congo",
        "Volta-Congo",
        "Benue-Congo",
        "Bantoid",
        "Southern Bantoid",
        "Narrow Bantu",
        "East Bantu",
        "Northeast Savanna Bantu",
        "Northeast Coastal Bantu",
        "Coastal NEC Bantu",
        "Sabaki-Swahili",
        "Swahili (G.40)",
        "Mombasa-Lamu-Inland Swahili",
        "Swahili"
    ],
    "Swedish": [
        "Indo-European",
        "Classical Indo-European",
        "Germanic",
        "Northwest Germanic",
        "North Germanic",
        "North Scandinavian",
        "East-Central Swedic",
        "East Swedic",
        "Swedish"
    ],
    "Thai": [
        "Tai-Kadai",
        "Kam-Tai",
        "Daic-Beic",
        "Daic",
        "Central-Southwestern Tai",
        "Wenma-Southwestern Tai",
        "Sapa-Southwestern Tai",
        "Southwestern Tai",
        "Southwestern Thai PH",
        "Lao-Thai",
        "Thai"
    ],
    "Tigrinya": [
        "Afro-Asiatic",
        "Semitic",
        "West Semitic",
        "Ethiosemitic",
        "Tigrinya"
    ],
    "Tsonga": [
        "Atlantic-Congo",
        "Volta-Congo",
        "Benue-Congo",
        "Bantoid",
        "Southern Bantoid",
        "Narrow Bantu",
        "East Bantu",
        "Southern Bantu",
        "Nuclear Southern Bantu",
        "Dimsuffix Southern Bantu",
        "Nguni-Tsonga-Copi",
        "Tsonga-Copi",
        "Tswa-Ronga (S.50)",
        "Tsongan",
        "Tsonga"
    ],
    "Tswa": [
        "Atlantic-Congo",
        "Volta-Congo",
        "Benue-Congo",
        "Bantoid",
        "Southern Bantoid",
        "Narrow Bantu",
        "East Bantu",
        "Southern Bantu",
        "Nuclear Southern Bantu",
        "Dimsuffix Southern Bantu",
        "Nguni-Tsonga-Copi",
        "Tsonga-Copi",
        "Tswa-Ronga (S.50)",
        "Tswa"
    ],
    "Tswana": [
        "Atlantic-Congo",
        "Volta-Congo",
        "Benue-Congo",
        "Bantoid",
        "Southern Bantoid",
        "Narrow Bantu",
        "East Bantu",
        "Southern Bantu",
        "Nuclear Southern Bantu",
        "Dimsuffix Southern Bantu",
        "Sotho-Tswana (S.30)",
        "Western Sotho-Tswana",
        "Central Sotho-Tswana",
        "Tswana"
    ],
    "Tunisian Arabic": [
        "Afro-Asiatic",
        "Semitic",
        "West Semitic",
        "Central Semitic",
        "Arabian",
        "Arabic",
        "North African Arabic",
        "Malta-Tunisian Arabic",
        "Tunisian Arabic"
    ],
    "Urhobo": [
        "Atlantic-Congo",
        "Volta-Congo",
        "Benue-Congo",
        "Akpes-Edoid",
        "Edoid",
        "Southwestern Edoid",
        "Urhobo"
    ],
    "Western Armenian": [
        "Indo-European",
        "Classical Indo-European",
        "Armenic",
        "Eastern-Western Armenian",
        "Western Armenian"
    ],
    "Yongbei Zhuang": [
        "Tai-Kadai",
        "Kam-Tai",
        "Daic-Beic",
        "Daic",
        "Northern Daic-Sek",
        "Northern Daic",
        "Yongnan-Yongbei",
        "Yongbei Zhuang"
    ],
    "Yue Chinese": [
        "Sino-Tibetan",
        "Sinitic",
        "Classical-Middle-Modern Sinitic",
        "Middle-Modern Sinitic",
        "Yue-Pinghua",
        "Yue Chinese"
    ],
    "Zulu": [
        "Atlantic-Congo",
        "Volta-Congo",
        "Benue-Congo",
        "Bantoid",
        "Southern Bantoid",
        "Narrow Bantu",
        "East Bantu",
        "Southern Bantu",
        "Nuclear Southern Bantu",
        "Dimsuffix Southern Bantu",
        "Nguni-Tsonga-Copi",
        "Nguni (S.40)",
        "Nuclear Nguni",
        "Southern Ndebele-Lowland",
        "Zulu"
    ]
};